//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfAppCarSharing
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car_Reservation
    {
        public int id { get; set; }
        public int Order_id { get; set; }
        public int Tarriff_id { get; set; }
        public System.DateTime Time_start { get; set; }
        public System.DateTime Time_end { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Tarriff Tarriff { get; set; }
    }
}
