//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfAppCarSharing
{
    using System;
    using System.Collections.Generic;
    
    public partial class MainTenance
    {
        public int id { get; set; }
        public int Specification_id { get; set; }
        public int Master_id { get; set; }
        public int Car_id { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual AutoPark AutoPark { get; set; }
        public virtual Master Master { get; set; }
        public virtual Specification_For_MainTenance Specification_For_MainTenance { get; set; }
    }
}
