//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfAppCarSharing
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Material()
        {
            this.Sets_of_Materials_For_specifications = new HashSet<Sets_of_Materials_For_specifications>();
        }
    
        public int id { get; set; }
        public int Item_id { get; set; }
        public string Material_Name { get; set; }
        public string Dimension { get; set; }
    
        public virtual Items_For_CarSharing Items_For_CarSharing { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sets_of_Materials_For_specifications> Sets_of_Materials_For_specifications { get; set; }
    }
}
