//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfAppCarSharing
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Customs
    {
        public int id { get; set; }
        public int Order_id { get; set; }
        public int Item_id { get; set; }
        public int Order_Items_Quantity { get; set; }
        public int Custom_Cost { get; set; }
    
        public virtual Items_For_CarSharing Items_For_CarSharing { get; set; }
        public virtual Order Order { get; set; }
    }
}
