//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfAppCarSharing
{
    using System;
    using System.Collections.Generic;
    
    public partial class Specification_For_MainTenance
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Specification_For_MainTenance()
        {
            this.MainTenances = new HashSet<MainTenance>();
        }
    
        public int id { get; set; }
        public string Specification_Name { get; set; }
        public int Service_Creator_id { get; set; }
        public int Set_Of_Materials_id { get; set; }
        public int Spec_Quantity { get; set; }
        public int Spec_Cost { get; set; }
    
        public virtual Client Client { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MainTenance> MainTenances { get; set; }
    }
}
