//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfAppCarSharing
{
    using System;
    using System.Collections.Generic;
    
    public partial class System_Accounts
    {
        public int id { get; set; }
        public int User_Id { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public byte System_role { get; set; }
        public bool IsBlock { get; set; }
        public Nullable<bool> IsFirst { get; set; }
    
        public virtual User User { get; set; }
    }
}
