//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfAppCarSharing
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarriff
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tarriff()
        {
            this.Car_Reservation = new HashSet<Car_Reservation>();
        }
    
        public int id { get; set; }
        public int Item_id { get; set; }
        public int Tarriff_Name { get; set; }
        public int Car_id { get; set; }
    
        public virtual AutoPark AutoPark { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Car_Reservation> Car_Reservation { get; set; }
        public virtual Items_For_CarSharing Items_For_CarSharing { get; set; }
    }
}
